language: nim
sudo: required
services:
  - docker
before_install:
  - docker pull yglukhov/nim-base
script:
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-base nim --version
  - docker run -v "$(pwd):/project" -w /project yglukhov/nim-base ls -la