name: Code Linter

on: [pull_request]

jobs:
  nimlint:
    name: runner / nimlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: nimlint-github-pr-review
      - uses: reviewdog/action-nimlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          src: 'src/*.nim'